from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing_page_view, name='landing_page'),
    path('login/', views.parent_login_view, name='parent_login'),
    path('dashboard/', views.parent_dashboard_view, name='parent_dashboard'),
    path('logout/', views.parent_logout_view, name='parent_logout'),
    
    path('teacher/', views.teacher_login_view, name='teacher_login'),
    path('teacher/dashboard/', views.teacher_dashboard_view, name='teacher_dashboard'),
    path('teacher/logout/', views.teacher_logout_view, name='teacher_logout'),
    path('teacher/class/<int:class_id>/attendance/', views.mark_attendance_view, name='mark_attendance'),
    path('teacher/class/<int:class_id>/monthly_attendance/', views.monthly_attendance_view, name='monthly_attendance'),
    path('teacher/class/<int:class_id>/marks/', views.enter_marks_view, name='enter_marks'),
    path('teacher/class/<int:class_id>/tasks/', views.manage_tasks_view, name='manage_tasks'),
    path('parent/task/<int:task_id>/complete/', views.parent_complete_task, name='parent_complete_task'),
    path('parent/task/<int:completion_id>/delete/', views.parent_delete_completion, name='parent_delete_completion'),
    path('teacher/completion/<int:completion_id>/verify/', views.teacher_verify_completion, name='teacher_verify_completion'),
    path('teacher/task/<int:task_id>/delete/', views.delete_task_view, name='delete_task'),
    
    path('portal/login/', views.admin_login_view, name='admin_login'),
    path('portal/logout/', views.admin_logout_view, name='admin_logout'),
    path('portal/dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('portal/working-days/', views.admin_working_days_view, name='admin_working_days'),
    path('portal/classes/', views.admin_classes_view, name='admin_classes'),
    path('portal/classes/<int:class_id>/edit/', views.admin_edit_class_view, name='admin_edit_class'),
    path('portal/classes/<int:class_id>/delete/', views.admin_delete_class_view, name='admin_delete_class'),
    path('portal/classes/<int:class_id>/subjects/', views.admin_subjects_view, name='admin_subjects'),
    path('portal/subjects/<int:subject_id>/edit/', views.admin_edit_subject_view, name='admin_edit_subject'),
    path('portal/subjects/<int:subject_id>/delete/', views.admin_delete_subject_view, name='admin_delete_subject'),
    path('portal/class/<int:class_id>/marks/view/', views.view_marks_view, name='view_marks'),
    path('portal/students/', views.admin_students_view, name='admin_students'),
    path('portal/students/<int:student_id>/edit/', views.admin_edit_student_view, name='admin_edit_student'),
    path('portal/students/<int:student_id>/delete/', views.admin_delete_student_view, name='admin_delete_student'),
    path('portal/students/<int:student_id>/detail/', views.admin_student_detail_view, name='admin_student_detail'),
    path('portal/students/bulk-delete/', views.admin_bulk_delete_students_view, name='admin_bulk_delete_students'),
    path('portal/students/bulk/', views.admin_bulk_students_view, name='admin_bulk_students'),
    path('portal/teachers/', views.admin_teachers_view, name='admin_teachers'),
    path('portal/teachers/<int:teacher_id>/edit/', views.admin_edit_teacher_view, name='admin_edit_teacher'),
    path('portal/teachers/<int:teacher_id>/delete/', views.admin_delete_teacher_view, name='admin_delete_teacher'),
    path('portal/teachers/bulk/', views.admin_bulk_teachers_view, name='admin_bulk_teachers'),
    path('portal/exams/', views.admin_exams_view, name='admin_exams'),
    path('portal/exams/<int:exam_id>/edit/', views.admin_edit_exam_view, name='admin_edit_exam'),
    path('portal/exams/<int:exam_id>/delete/', views.admin_delete_exam_view, name='admin_delete_exam'),
    
    # Centre Management URLs
    path('portal/centres/', views.admin_centres_view, name='admin_centres'),
    path('portal/centres/<int:centre_id>/edit/', views.admin_edit_centre_view, name='admin_edit_centre'),
    path('portal/centres/<int:centre_id>/delete/', views.admin_delete_centre_view, name='admin_delete_centre'),
    path('portal/switch-centre/<int:centre_id>/', views.admin_switch_centre_view, name='admin_switch_centre'),
]
