# Generated by Django 5.2.8 on 2026-05-17 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_exam_passing_marks_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Physics, Chemistry', max_length=100)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='tuition.classgroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'class_group')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='markentry',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='tuition.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together={('student', 'exam', 'subject')},
        ),
    ]
