# Generated by Django 5.2.8 on 2026-05-17 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_subject_alter_markentry_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Town Branch, City Branch', max_length=100, unique=True)),
                ('code', models.CharField(help_text='e.g. TCNTR', max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(help_text='e.g. Class 10 Science', max_length=100),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='tuition.centre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='tuition.centre'),
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('name', 'centre')},
        ),
    ]
