# Generated by Django 5.2.8 on 2026-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_hometask'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_working_day', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, help_text='e.g., Public Holiday, Sunday', max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
